# Generated by Django 4.2.16 on 2024-10-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
